#!/usr/bin/env python3
"""Run pytest with one isolated, inspectable artifact directory."""
from __future__ import annotations

import argparse
import json
import os
import platform
import re
import subprocess
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ARTIFACT_ROOT = REPO_ROOT / "artifacts" / "test-runs"
_SAFE_RUN_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$")
_UUID = re.compile(
    r"(?i)\b[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-"
    r"[89ab][0-9a-f]{3}-[0-9a-f]{12}\b"
)
_SECRET = re.compile(
    r"(?i)(?:[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|"
    # Decimal values such as 39.980000000000004 are not card numbers. Requiring the
    # digit run to be bounded by neither a digit nor a decimal point preserves the
    # useful contiguous/spaced/hyphenated card check without failing on money logs.
    # Hex boundaries also exclude numeric stretches inside UUID correlation IDs.
    r"(?<![\dA-F.])(?:\d[ -]?){13,19}(?![\dA-F.])|"
    r"\b(?:cvv|cvc|security code)\b\D{0,10}\d{3,4})"
)


def new_run_id() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{timestamp}-{uuid.uuid4().hex[:8]}"


def create_artifact_dir(root: Path, run_id: str) -> Path:
    if not _SAFE_RUN_ID.fullmatch(run_id) or run_id in {".", ".."}:
        raise ValueError("run id must contain only letters, numbers, '.', '_' or '-'")
    path = root / run_id
    path.mkdir(parents=True, exist_ok=False)
    return path


def scan_for_secrets(paths: list[Path]) -> list[dict[str, str | int]]:
    """Return locations of obvious raw secrets without echoing the matched value."""
    findings: list[dict[str, str | int]] = []
    for path in paths:
        if not path.exists():
            continue
        for line_number, line in enumerate(path.read_text(errors="replace").splitlines(), 1):
            # Correlation IDs are canonical UUIDs and can contain a chance run of 13+
            # decimal digits across their hyphens. Remove them before the card-like scan.
            if _SECRET.search(_UUID.sub("***", line)):
                findings.append({"file": path.name, "line": line_number})
    return findings


def _git_commit() -> str | None:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False,
    )
    return result.stdout.strip() or None if result.returncode == 0 else None


def _write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", help="artifact directory name (generated by default)")
    parser.add_argument("--artifact-root", type=Path, default=DEFAULT_ARTIFACT_ROOT,
                        help=argparse.SUPPRESS)
    args, pytest_args = parser.parse_known_args(argv)

    run_id = args.run_id or new_run_id()
    try:
        artifact_dir = create_artifact_dir(args.artifact_root.resolve(), run_id)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))

    files = {name: artifact_dir / name for name in (
        "metadata.json", "summary.json", "console.log", "pytest.log", "junit.xml",
        "agent.jsonl", "api.jsonl",
    )}
    for name in ("pytest.log", "agent.jsonl", "api.jsonl"):
        files[name].touch()

    started = time.time()
    _write_json(files["metadata.json"], {
        "run_id": run_id,
        "started_at": datetime.now(timezone.utc).isoformat(),
        "git_commit": _git_commit(),
        "python": sys.version,
        "platform": platform.platform(),
        "pytest_args": pytest_args,
    })

    env = os.environ.copy()
    env.update({
        "TEST_RUN_ID": run_id,
        "TEST_ARTIFACT_DIR": str(artifact_dir),
        "LOG_DIR": str(artifact_dir),
    })
    # The client intentionally requires credentials in production. Local tests use a
    # scripted transport, so safe non-secret defaults make a clean checkout hermetic.
    env.setdefault("AVIS_API_URL", "https://local.test.invalid")
    env.setdefault("AVIS_API_KEY", "local-test-key")

    command = [sys.executable, "-m", "pytest", *pytest_args,
               f"--junitxml={files['junit.xml']}", f"--log-file={files['pytest.log']}",
               "--log-file-level=INFO"]
    with files["console.log"].open("w") as console:
        process = subprocess.Popen(
            command, cwd=REPO_ROOT, env=env, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        )
        assert process.stdout is not None
        for line in process.stdout:
            sys.stdout.write(line)
            sys.stdout.flush()
            console.write(line)
            console.flush()
        return_code = process.wait()

    summary = {}
    if files["summary.json"].exists():
        try:
            summary = json.loads(files["summary.json"].read_text())
        except (json.JSONDecodeError, OSError):
            summary = {}
    findings = scan_for_secrets([
        files["console.log"], files["pytest.log"], files["junit.xml"],
        files["agent.jsonl"], files["api.jsonl"],
    ])
    final_exit_code = return_code or (2 if findings else 0)
    summary.update({
        "run_id": run_id,
        "exit_code": final_exit_code,
        "pytest_exit_code": return_code,
        "duration_seconds": round(time.time() - started, 3),
        "completed_at": datetime.now(timezone.utc).isoformat(),
        "artifact_secret_scan": {"passed": not findings, "findings": findings},
    })
    _write_json(files["summary.json"], summary)

    print(f"\nTest artifacts: {artifact_dir}")
    if findings:
        print(f"WARNING: obvious secret patterns found in {len(findings)} artifact line(s).")
    return final_exit_code


if __name__ == "__main__":
    raise SystemExit(main())
